// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcjfiguglbgzmycmxodn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjamZpZ3VnbGJnem15Y214b2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTIwNTQsImV4cCI6MjA3MjcyODA1NH0.w3TCJph-pRi4PQsCfYWuDU0yW10lllZ59QDnR9AobCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});